CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    avatar_url VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL,
    nickname VARCHAR(50),
    password VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL,
    username VARCHAR(50) NOT NULL,
    theme VARCHAR(10) NOT NULL,
    CONSTRAINT uk_users_username UNIQUE (username)
);

CREATE TABLE channels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    description VARCHAR(255),
    invite_code VARCHAR(20),
    is_muted BOOLEAN NOT NULL,
    is_public BOOLEAN NOT NULL,
    name VARCHAR(100) NOT NULL,
    creator_id BIGINT NOT NULL,
    CONSTRAINT uk_channels_invite_code UNIQUE (invite_code),
    CONSTRAINT fk_channels_creator FOREIGN KEY (creator_id) REFERENCES users (id)
);

CREATE TABLE channel_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    history_level VARCHAR(20) NOT NULL,
    history_limit INT,
    joined_at TIMESTAMP(6) NOT NULL,
    role VARCHAR(20) NOT NULL,
    channel_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT uk_channel_members_channel_user UNIQUE (channel_id, user_id),
    CONSTRAINT fk_channel_members_channel FOREIGN KEY (channel_id) REFERENCES channels (id),
    CONSTRAINT fk_channel_members_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE private_chats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    user1_id BIGINT NOT NULL,
    user2_id BIGINT NOT NULL,
    initiator_id BIGINT NOT NULL,
    status VARCHAR(10) NOT NULL,
    CONSTRAINT uk_private_chats_users UNIQUE (user1_id, user2_id),
    CONSTRAINT fk_private_chats_user1 FOREIGN KEY (user1_id) REFERENCES users (id),
    CONSTRAINT fk_private_chats_user2 FOREIGN KEY (user2_id) REFERENCES users (id),
    CONSTRAINT fk_private_chats_initiator FOREIGN KEY (initiator_id) REFERENCES users (id)
);

CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT,
    created_at TIMESTAMP(6) NOT NULL,
    file_name VARCHAR(255),
    file_path VARCHAR(500),
    is_recalled BOOLEAN NOT NULL,
    type VARCHAR(20) NOT NULL,
    channel_id BIGINT,
    sender_id BIGINT NOT NULL,
    private_chat_id BIGINT,
    CONSTRAINT fk_messages_channel FOREIGN KEY (channel_id) REFERENCES channels (id),
    CONSTRAINT fk_messages_sender FOREIGN KEY (sender_id) REFERENCES users (id),
    CONSTRAINT fk_messages_private_chat FOREIGN KEY (private_chat_id) REFERENCES private_chats (id)
);

CREATE INDEX idx_channel_created ON messages (channel_id, created_at);

CREATE TABLE message_reads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    read_at TIMESTAMP(6) NOT NULL,
    message_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT uk_message_reads_message_user UNIQUE (message_id, user_id),
    CONSTRAINT fk_message_reads_message FOREIGN KEY (message_id) REFERENCES messages (id),
    CONSTRAINT fk_message_reads_user FOREIGN KEY (user_id) REFERENCES users (id)
);

